### ISSUE TITLE
[Feature Request] Flatpak Support

### ISSUE THREAD

**Issue by MelihDarcanxyz** [FreeterApp/Freeter#15]
Hi, thanks for great work! Is it possible or planned to add Flatpak support in the future?

**Comment by Beryesa** [comment]
Ooh, I came here for that too, you're faster :smile: 
I can try to make a manifest file, but it would be more helpful to have official endorsement from the developers and a stable release first.

**Comment by alexk111** [comment]
Thanks for the feedback! Added to the planned features: https://community.freeter.io/topic/2/planned-features

**Comment by Sush-ruta** [comment]
Hi, thanks for another awesome addition to the Linux app ecosystem. One suggestion: if you could release it as an AppImage too, people who don't want to rely on Flatpak can also enjoy this. Thanks again. :)
