### ISSUE TITLE
Download for MAC M1 cannot be run

### ISSUE THREAD

**Issue by haintwork** [FreeterApp/Freeter#18]
Error message:
```
“Freeter” is damaged and can’t be opened. You should move it to the Trash.
```
Freeter downloaded version: `Freeter-2.3.1-beta-mac-arm64`
My MAC is M1 chip.
Mac OS Monterey 12.6.6 (21G646)
<img width="372" alt="Screen Shot 2024-05-17 at 11 00 48" src="https://github.com/FreeterApp/Freeter/assets/22661795/6ec0779c-9903-4c41-b8bc-93017ffd98f0">

**Comment by alexk111** [comment]
Execute the following command line in the Terminal: 
`xattr -cr /Applications/Freeter.app`

Then try to run Freeter again.

**Comment by haintwork** [comment]
Thanks @alexk111 , it's working now. Wonder what is the root cause?

**Comment by alexk111** [comment]
👍

> Wonder what is the root cause?

It occurs because Freeter executable is not code-signed/notarized.

**Comment by kryptonianson** [comment]
could you all sign it so that the install/deployment is more secure? It would sure smooth out the workflow. That would really be great. Thank you for considering.
